### ISSUE TITLE
1.20.6 error

### ISSUE THREAD

**Issue by envizar** [sovdeeth/skript-particle#2]
### Environment Information

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: 1.20.6-90-b149584 (MC: 1.20.6)
[Skript] Skript Version: 2.8.5 (skriptlang-github)
[Skript] Installed Skript Addons:
[Skript]  - skript-particle v1.3.0 (https://github.com/sovdeeth/skript-particle)
[Skript] Installed dependencies: None
```

### Bug Description

Error on startup
https://paste.denizenscript.com/View/122941

### Steps to Reproduce

Start 1.20.6 paper server with Skript and skript-particle

**Comment by sovdeeth** [comment]
I've been waiting for paper to make a stable 1.20.6 release, but I should probably just fix it at this point tbh, dunno when they're going to get around to releasing one.

**Comment by sovdeeth** [comment]
oh right 1.3.1 should have fixed this
