### ISSUE TITLE
DustTransition

### ISSUE THREAD

**Issue by leakclient** [sovdeeth/skript-particle#5]
Hello there!
I tried makind a custom particle section for particles, but gave me a error. Im really confused and don't know any further. If you need my code, here it is:

command /powerlasers:
    permission: novainc.ultratester
    trigger:
        loop 150 times:
            set {_laserA} to line from location(122.5, 57.0, 40.0) to location(122.5, 57.0, 43.5)
            set {_laserA}'s particle to dustTransition(red, green, 10)
            draw the shape {_laserA}
            wait 1 tick

**Comment by sovdeeth** [comment]
Please use the linked discord on the GitHub page for help; this is for bug reports and suggestions :)
